### PR TITLE
Feature: Adding Loenn plugin trigger for Map Makers

### PR DESCRIPTION
**Pull request by KristanLaimon**
Somehow I didn't realize there is already a pull request to add this feature (#1) . I did it anyways 🤙🏼 
# Loenn Plugin to toggle mod
- This has a lua implementation and some validations to keep original user's config of the mod.
- That's it 🦊 

image

And the property...
image

### CODE REVIEW

**Comment by SneezingCactus** [comment]
Hey there! i'm making a helper update for Portaline, which will add some useful entities such as emancipation grills, and i'd love to have this in the base mod. May i use your code? I'll make sure to credit you on the GameBanana page (alongside @Saplonily)

i've also noticed that your Portaline+ is using the same id as the base Portaline, which is not recommended. Would you mind taking Portaline+ down in favour of the new update? Thank you

**Comment by KristanLaimon** [comment]
Of course!, I'd love to see this implemented in the original. I'll reopen the pull request by the way🦊💞

**Comment by SneezingCactus** [comment]
awesome, thank you!!! will be merging the pr now

**Comment by Saplonily** [comment]
lol, thanks for doing these!

**Pull request merged**
